services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: cakephp_app
    env_file:
      - .env
    volumes:
      - ./app:/var/www/html
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: cakephp_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgres:
    image: postgres:15
    container_name: cakephp_postgres
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/db/data/${DB_NAME}:/var/lib/postgresql/data
